---
# Apply latest style guide and new cops
AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - '_snippets/*'
  Include:
  - 'Gemfile'
  - 'Rakefile'
  - '**/*.rb'

# Ignore block length where unavoidable (e.g., frameworks using blocks)
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - 'spec/**/*'
    - Rakefile
    - app/application/controllers/**/*.rb # Roda's nested controllers require large blocks
    - spec/**/* # Minitest's nested test structure requires large blocks
    - Rakefile # Rake namespaces produce large blocks

Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented