---
development:
  # Infrastructure
  DB_FILENAME:    app/infrastructure/database/local/dev.db
  YOUTUBE_TOKEN:  This_Is_A_Sample_Youtube_Token
  # Application
  APP_HOST: http://localhost:9000
  SESSION_SECRET: <some secret>

app_test:
  # Infrastructure
  DB_FILENAME:    app/infrastructure/database/local/test.db
  # Application
  APP_HOST: http://localhost:9000
  
test:
  # Infrastructure
  DB_FILENAME:    app/infrastructure/database/local/test.db
  YOUTUBE_TOKEN:  This_Is_A_Sample_Youtube_Token
  # Application
  APP_HOST: http://localhost:9000
  SESSION_SECRET: <some secret>

production:
  
  YOUTUBE_TOKEN:  This_Is_A_Sample_Youtube_Token
  # Application
  APP_HOST: http://url.to.app
  SESSION_SECRET: <some secret>
  