---
development:
  API_HOST: http://localhost:9000
  # Infrastructure
  DB_FILENAME:    app/infrastructure/database/local/dev.db
  YOUTUBE_TOKEN:  This_Is_A_Sample_Youtube_Token
  SESSION_SECRET: <some secret>
  REDISCLOUD_URL: <url assigned by Redis>

app_test:
  API_HOST: http://localhost:9000
  # Infrastructure
  DB_FILENAME:    app/infrastructure/database/local/test.db
  REDISCLOUD_URL: <url assigned by Redis>
  
test:
  API_HOST: http://localhost:9000
  # Infrastructure
  DB_FILENAME:    app/infrastructure/database/local/test.db
  YOUTUBE_TOKEN:  This_Is_A_Sample_Youtube_Token
  SESSION_SECRET: <some secret>
  REDISCLOUD_URL: <url assigned by Redis>

production:
  API_HOST: http://url.to.app
  # - assign DATABASE_URL in production
  YOUTUBE_TOKEN:  This_Is_A_Sample_Youtube_Token
  SESSION_SECRET: <some secret>
  REDISCLOUD_URL: <url assigned by Redis>
  